name: Autoapprove

on:
  pull_request:

concurrency:
  group: approve-${{ github.event.pull_request.number }}

jobs:
  approve:
    runs-on: ubuntu-slim
    permissions:
      pull-requests: write
    steps:
      - uses: plengauer/autoapprove@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # TODO give "approve PR permission in settings"
          user_to_approve: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
